site_name: AppBox Docs
site_description: AppBox Documentation
site_url: https://docs.getappbox.com
copyright: Copyright © AppBox
repo_url: https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation
repo_name: AppBox
remote_branch: gh-pages
dev_addr: 127.0.0.1:2000 
edit_uri: blob/master/docs/

# Google Analytics
google_analytics:
  - 'UA-85215717-4'
  - 'auto'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation'
    - type: 'twitter'
      link: 'https://twitter.com/AppBoxHQ'

# Configuration
theme:
  name: 'material'
  language: 'en'
  logo: Images/AppBoxIcon.png
  favicon: Images/AppBoxIcon.png
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search:
      lang: en
  - awesome-pages
  - minify:
      minify_html: true    
extra:
  generator: false