///
/// Copyright (c) 2016 Dropbox, Inc. All rights reserved.
///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>

#import "DBSerializableProtocol.h"

@class DBFILESGetThumbnailBatchResult;
@class DBFILESGetThumbnailBatchResultEntry;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - API Object

///
/// The `GetThumbnailBatchResult` struct.
///
/// This class implements the `DBSerializable` protocol (serialize and
/// deserialize instance methods), which is required for all Obj-C SDK API route
/// objects.
///
@interface DBFILESGetThumbnailBatchResult : NSObject <DBSerializable, NSCopying>

#pragma mark - Instance fields

/// List of files and their thumbnails.
@property (nonatomic, readonly) NSArray<DBFILESGetThumbnailBatchResultEntry *> *entries;

#pragma mark - Constructors

///
/// Full constructor for the struct (exposes all instance variables).
///
/// @param entries List of files and their thumbnails.
///
/// @return An initialized instance.
///
- (instancetype)initWithEntries:(NSArray<DBFILESGetThumbnailBatchResultEntry *> *)entries;

- (instancetype)init NS_UNAVAILABLE;

@end

#pragma mark - Serializer Object

///
/// The serialization class for the `GetThumbnailBatchResult` struct.
///
@interface DBFILESGetThumbnailBatchResultSerializer : NSObject

///
/// Serializes `DBFILESGetThumbnailBatchResult` instances.
///
/// @param instance An instance of the `DBFILESGetThumbnailBatchResult` API
/// object.
///
/// @return A json-compatible dictionary representation of the
/// `DBFILESGetThumbnailBatchResult` API object.
///
+ (nullable NSDictionary<NSString *, id> *)serialize:(DBFILESGetThumbnailBatchResult *)instance;

///
/// Deserializes `DBFILESGetThumbnailBatchResult` instances.
///
/// @param dict A json-compatible dictionary representation of the
/// `DBFILESGetThumbnailBatchResult` API object.
///
/// @return An instantiation of the `DBFILESGetThumbnailBatchResult` object.
///
+ (DBFILESGetThumbnailBatchResult *)deserialize:(NSDictionary<NSString *, id> *)dict;

@end

NS_ASSUME_NONNULL_END
