///
/// Copyright (c) 2016 Dropbox, Inc. All rights reserved.
///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>

#import "DBSerializableProtocol.h"

@class DBTEAMDeleteSecondaryEmailResult;
@class DBTEAMUserDeleteEmailsResult;
@class DBTEAMUserSelectorArg;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - API Object

///
/// The `UserDeleteEmailsResult` struct.
///
/// This class implements the `DBSerializable` protocol (serialize and
/// deserialize instance methods), which is required for all Obj-C SDK API route
/// objects.
///
@interface DBTEAMUserDeleteEmailsResult : NSObject <DBSerializable, NSCopying>

#pragma mark - Instance fields

/// (no description).
@property (nonatomic, readonly) DBTEAMUserSelectorArg *user;

/// (no description).
@property (nonatomic, readonly) NSArray<DBTEAMDeleteSecondaryEmailResult *> *results;

#pragma mark - Constructors

///
/// Full constructor for the struct (exposes all instance variables).
///
/// @param user (no description).
/// @param results (no description).
///
/// @return An initialized instance.
///
- (instancetype)initWithUser:(DBTEAMUserSelectorArg *)user
                     results:(NSArray<DBTEAMDeleteSecondaryEmailResult *> *)results;

- (instancetype)init NS_UNAVAILABLE;

@end

#pragma mark - Serializer Object

///
/// The serialization class for the `UserDeleteEmailsResult` struct.
///
@interface DBTEAMUserDeleteEmailsResultSerializer : NSObject

///
/// Serializes `DBTEAMUserDeleteEmailsResult` instances.
///
/// @param instance An instance of the `DBTEAMUserDeleteEmailsResult` API
/// object.
///
/// @return A json-compatible dictionary representation of the
/// `DBTEAMUserDeleteEmailsResult` API object.
///
+ (nullable NSDictionary<NSString *, id> *)serialize:(DBTEAMUserDeleteEmailsResult *)instance;

///
/// Deserializes `DBTEAMUserDeleteEmailsResult` instances.
///
/// @param dict A json-compatible dictionary representation of the
/// `DBTEAMUserDeleteEmailsResult` API object.
///
/// @return An instantiation of the `DBTEAMUserDeleteEmailsResult` object.
///
+ (DBTEAMUserDeleteEmailsResult *)deserialize:(NSDictionary<NSString *, id> *)dict;

@end

NS_ASSUME_NONNULL_END
