///
/// Copyright (c) 2016 Dropbox, Inc. All rights reserved.
///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>

#import "DBSerializableProtocol.h"

@class DBTEAMLOGNoteAclLinkDetails;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - API Object

///
/// The `NoteAclLinkDetails` struct.
///
/// Changed Paper doc to link-accessible.
///
/// This class implements the `DBSerializable` protocol (serialize and
/// deserialize instance methods), which is required for all Obj-C SDK API route
/// objects.
///
@interface DBTEAMLOGNoteAclLinkDetails : NSObject <DBSerializable, NSCopying>

#pragma mark - Instance fields

#pragma mark - Constructors

///
/// Full constructor for the struct (exposes all instance variables).
///
/// @return An initialized instance.
///
- (instancetype)initDefault;

- (instancetype)init NS_UNAVAILABLE;

@end

#pragma mark - Serializer Object

///
/// The serialization class for the `NoteAclLinkDetails` struct.
///
@interface DBTEAMLOGNoteAclLinkDetailsSerializer : NSObject

///
/// Serializes `DBTEAMLOGNoteAclLinkDetails` instances.
///
/// @param instance An instance of the `DBTEAMLOGNoteAclLinkDetails` API object.
///
/// @return A json-compatible dictionary representation of the
/// `DBTEAMLOGNoteAclLinkDetails` API object.
///
+ (nullable NSDictionary<NSString *, id> *)serialize:(DBTEAMLOGNoteAclLinkDetails *)instance;

///
/// Deserializes `DBTEAMLOGNoteAclLinkDetails` instances.
///
/// @param dict A json-compatible dictionary representation of the
/// `DBTEAMLOGNoteAclLinkDetails` API object.
///
/// @return An instantiation of the `DBTEAMLOGNoteAclLinkDetails` object.
///
+ (DBTEAMLOGNoteAclLinkDetails *)deserialize:(NSDictionary<NSString *, id> *)dict;

@end

NS_ASSUME_NONNULL_END
