///
/// Copyright (c) 2016 Dropbox, Inc. All rights reserved.
///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>

#import "DBSerializableProtocol.h"

@class DBTEAMLOGRewindPolicy;
@class DBTEAMLOGRewindPolicyChangedDetails;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - API Object

///
/// The `RewindPolicyChangedDetails` struct.
///
/// Changed Rewind policy for team.
///
/// This class implements the `DBSerializable` protocol (serialize and
/// deserialize instance methods), which is required for all Obj-C SDK API route
/// objects.
///
@interface DBTEAMLOGRewindPolicyChangedDetails : NSObject <DBSerializable, NSCopying>

#pragma mark - Instance fields

/// New Dropbox Rewind policy.
@property (nonatomic, readonly) DBTEAMLOGRewindPolicy *dNewValue;

/// Previous Dropbox Rewind policy.
@property (nonatomic, readonly) DBTEAMLOGRewindPolicy *previousValue;

#pragma mark - Constructors

///
/// Full constructor for the struct (exposes all instance variables).
///
/// @param dNewValue New Dropbox Rewind policy.
/// @param previousValue Previous Dropbox Rewind policy.
///
/// @return An initialized instance.
///
- (instancetype)initWithDNewValue:(DBTEAMLOGRewindPolicy *)dNewValue
                    previousValue:(DBTEAMLOGRewindPolicy *)previousValue;

- (instancetype)init NS_UNAVAILABLE;

@end

#pragma mark - Serializer Object

///
/// The serialization class for the `RewindPolicyChangedDetails` struct.
///
@interface DBTEAMLOGRewindPolicyChangedDetailsSerializer : NSObject

///
/// Serializes `DBTEAMLOGRewindPolicyChangedDetails` instances.
///
/// @param instance An instance of the `DBTEAMLOGRewindPolicyChangedDetails` API
/// object.
///
/// @return A json-compatible dictionary representation of the
/// `DBTEAMLOGRewindPolicyChangedDetails` API object.
///
+ (nullable NSDictionary<NSString *, id> *)serialize:(DBTEAMLOGRewindPolicyChangedDetails *)instance;

///
/// Deserializes `DBTEAMLOGRewindPolicyChangedDetails` instances.
///
/// @param dict A json-compatible dictionary representation of the
/// `DBTEAMLOGRewindPolicyChangedDetails` API object.
///
/// @return An instantiation of the `DBTEAMLOGRewindPolicyChangedDetails`
/// object.
///
+ (DBTEAMLOGRewindPolicyChangedDetails *)deserialize:(NSDictionary<NSString *, id> *)dict;

@end

NS_ASSUME_NONNULL_END
