///
/// Copyright (c) 2016 Dropbox, Inc. All rights reserved.
///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>

#import "DBSerializableProtocol.h"

@class DBTEAMLOGDataResidencyMigrationRequestSuccessfulDetails;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - API Object

///
/// The `DataResidencyMigrationRequestSuccessfulDetails` struct.
///
/// Requested data residency migration for team data.
///
/// This class implements the `DBSerializable` protocol (serialize and
/// deserialize instance methods), which is required for all Obj-C SDK API route
/// objects.
///
@interface DBTEAMLOGDataResidencyMigrationRequestSuccessfulDetails : NSObject <DBSerializable, NSCopying>

#pragma mark - Instance fields

#pragma mark - Constructors

///
/// Full constructor for the struct (exposes all instance variables).
///
/// @return An initialized instance.
///
- (instancetype)initDefault;

- (instancetype)init NS_UNAVAILABLE;

@end

#pragma mark - Serializer Object

///
/// The serialization class for the
/// `DataResidencyMigrationRequestSuccessfulDetails` struct.
///
@interface DBTEAMLOGDataResidencyMigrationRequestSuccessfulDetailsSerializer : NSObject

///
/// Serializes `DBTEAMLOGDataResidencyMigrationRequestSuccessfulDetails`
/// instances.
///
/// @param instance An instance of the
/// `DBTEAMLOGDataResidencyMigrationRequestSuccessfulDetails` API object.
///
/// @return A json-compatible dictionary representation of the
/// `DBTEAMLOGDataResidencyMigrationRequestSuccessfulDetails` API object.
///
+ (nullable NSDictionary<NSString *, id> *)serialize:
    (DBTEAMLOGDataResidencyMigrationRequestSuccessfulDetails *)instance;

///
/// Deserializes `DBTEAMLOGDataResidencyMigrationRequestSuccessfulDetails`
/// instances.
///
/// @param dict A json-compatible dictionary representation of the
/// `DBTEAMLOGDataResidencyMigrationRequestSuccessfulDetails` API object.
///
/// @return An instantiation of the
/// `DBTEAMLOGDataResidencyMigrationRequestSuccessfulDetails` object.
///
+ (DBTEAMLOGDataResidencyMigrationRequestSuccessfulDetails *)deserialize:(NSDictionary<NSString *, id> *)dict;

@end

NS_ASSUME_NONNULL_END
