///
/// Copyright (c) 2016 Dropbox, Inc. All rights reserved.
///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>

#import "DBSerializableProtocol.h"

@class DBTEAMSharingAllowlistListResponse;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - API Object

///
/// The `SharingAllowlistListResponse` struct.
///
/// This class implements the `DBSerializable` protocol (serialize and
/// deserialize instance methods), which is required for all Obj-C SDK API route
/// objects.
///
@interface DBTEAMSharingAllowlistListResponse : NSObject <DBSerializable, NSCopying>

#pragma mark - Instance fields

/// List of domains represented by valid string representation (RFC-1034/5).
@property (nonatomic, readonly) NSArray<NSString *> *domains;

/// List of emails represented by valid string representation (RFC-5322/822).
@property (nonatomic, readonly) NSArray<NSString *> *emails;

/// If this is nonempty, there are more entries that can be fetched with
/// `sharingAllowlistListContinue`.
@property (nonatomic, readonly, copy) NSString *cursor;

/// if true indicates that more entries can be fetched with
/// `sharingAllowlistListContinue`.
@property (nonatomic, readonly) NSNumber *hasMore;

#pragma mark - Constructors

///
/// Full constructor for the struct (exposes all instance variables).
///
/// @param domains List of domains represented by valid string representation
/// (RFC-1034/5).
/// @param emails List of emails represented by valid string representation
/// (RFC-5322/822).
/// @param cursor If this is nonempty, there are more entries that can be
/// fetched with `sharingAllowlistListContinue`.
/// @param hasMore if true indicates that more entries can be fetched with
/// `sharingAllowlistListContinue`.
///
/// @return An initialized instance.
///
- (instancetype)initWithDomains:(NSArray<NSString *> *)domains
                         emails:(NSArray<NSString *> *)emails
                         cursor:(nullable NSString *)cursor
                        hasMore:(nullable NSNumber *)hasMore;

///
/// Convenience constructor (exposes only non-nullable instance variables with
/// no default value).
///
/// @param domains List of domains represented by valid string representation
/// (RFC-1034/5).
/// @param emails List of emails represented by valid string representation
/// (RFC-5322/822).
///
/// @return An initialized instance.
///
- (instancetype)initWithDomains:(NSArray<NSString *> *)domains emails:(NSArray<NSString *> *)emails;

- (instancetype)init NS_UNAVAILABLE;

@end

#pragma mark - Serializer Object

///
/// The serialization class for the `SharingAllowlistListResponse` struct.
///
@interface DBTEAMSharingAllowlistListResponseSerializer : NSObject

///
/// Serializes `DBTEAMSharingAllowlistListResponse` instances.
///
/// @param instance An instance of the `DBTEAMSharingAllowlistListResponse` API
/// object.
///
/// @return A json-compatible dictionary representation of the
/// `DBTEAMSharingAllowlistListResponse` API object.
///
+ (nullable NSDictionary<NSString *, id> *)serialize:(DBTEAMSharingAllowlistListResponse *)instance;

///
/// Deserializes `DBTEAMSharingAllowlistListResponse` instances.
///
/// @param dict A json-compatible dictionary representation of the
/// `DBTEAMSharingAllowlistListResponse` API object.
///
/// @return An instantiation of the `DBTEAMSharingAllowlistListResponse` object.
///
+ (DBTEAMSharingAllowlistListResponse *)deserialize:(NSDictionary<NSString *, id> *)dict;

@end

NS_ASSUME_NONNULL_END
