///
/// Copyright (c) 2016 Dropbox, Inc. All rights reserved.
///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>

#import "DBSerializableProtocol.h"

@class DBTEAMLOGSecondaryEmailDeletedDetails;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - API Object

///
/// The `SecondaryEmailDeletedDetails` struct.
///
/// Deleted secondary email.
///
/// This class implements the `DBSerializable` protocol (serialize and
/// deserialize instance methods), which is required for all Obj-C SDK API route
/// objects.
///
@interface DBTEAMLOGSecondaryEmailDeletedDetails : NSObject <DBSerializable, NSCopying>

#pragma mark - Instance fields

/// Deleted secondary email.
@property (nonatomic, readonly, copy) NSString *secondaryEmail;

#pragma mark - Constructors

///
/// Full constructor for the struct (exposes all instance variables).
///
/// @param secondaryEmail Deleted secondary email.
///
/// @return An initialized instance.
///
- (instancetype)initWithSecondaryEmail:(NSString *)secondaryEmail;

- (instancetype)init NS_UNAVAILABLE;

@end

#pragma mark - Serializer Object

///
/// The serialization class for the `SecondaryEmailDeletedDetails` struct.
///
@interface DBTEAMLOGSecondaryEmailDeletedDetailsSerializer : NSObject

///
/// Serializes `DBTEAMLOGSecondaryEmailDeletedDetails` instances.
///
/// @param instance An instance of the `DBTEAMLOGSecondaryEmailDeletedDetails`
/// API object.
///
/// @return A json-compatible dictionary representation of the
/// `DBTEAMLOGSecondaryEmailDeletedDetails` API object.
///
+ (nullable NSDictionary<NSString *, id> *)serialize:(DBTEAMLOGSecondaryEmailDeletedDetails *)instance;

///
/// Deserializes `DBTEAMLOGSecondaryEmailDeletedDetails` instances.
///
/// @param dict A json-compatible dictionary representation of the
/// `DBTEAMLOGSecondaryEmailDeletedDetails` API object.
///
/// @return An instantiation of the `DBTEAMLOGSecondaryEmailDeletedDetails`
/// object.
///
+ (DBTEAMLOGSecondaryEmailDeletedDetails *)deserialize:(NSDictionary<NSString *, id> *)dict;

@end

NS_ASSUME_NONNULL_END
