///
/// Copyright (c) 2016 Dropbox, Inc. All rights reserved.
///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>

#import "DBSerializableProtocol.h"

@class DBTEAMMembersGetInfoItemV2;
@class DBTEAMMembersGetInfoV2Result;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - API Object

///
/// The `MembersGetInfoV2Result` struct.
///
/// This class implements the `DBSerializable` protocol (serialize and
/// deserialize instance methods), which is required for all Obj-C SDK API route
/// objects.
///
@interface DBTEAMMembersGetInfoV2Result : NSObject <DBSerializable, NSCopying>

#pragma mark - Instance fields

/// List of team members info.
@property (nonatomic, readonly) NSArray<DBTEAMMembersGetInfoItemV2 *> *membersInfo;

#pragma mark - Constructors

///
/// Full constructor for the struct (exposes all instance variables).
///
/// @param membersInfo List of team members info.
///
/// @return An initialized instance.
///
- (instancetype)initWithMembersInfo:(NSArray<DBTEAMMembersGetInfoItemV2 *> *)membersInfo;

- (instancetype)init NS_UNAVAILABLE;

@end

#pragma mark - Serializer Object

///
/// The serialization class for the `MembersGetInfoV2Result` struct.
///
@interface DBTEAMMembersGetInfoV2ResultSerializer : NSObject

///
/// Serializes `DBTEAMMembersGetInfoV2Result` instances.
///
/// @param instance An instance of the `DBTEAMMembersGetInfoV2Result` API
/// object.
///
/// @return A json-compatible dictionary representation of the
/// `DBTEAMMembersGetInfoV2Result` API object.
///
+ (nullable NSDictionary<NSString *, id> *)serialize:(DBTEAMMembersGetInfoV2Result *)instance;

///
/// Deserializes `DBTEAMMembersGetInfoV2Result` instances.
///
/// @param dict A json-compatible dictionary representation of the
/// `DBTEAMMembersGetInfoV2Result` API object.
///
/// @return An instantiation of the `DBTEAMMembersGetInfoV2Result` object.
///
+ (DBTEAMMembersGetInfoV2Result *)deserialize:(NSDictionary<NSString *, id> *)dict;

@end

NS_ASSUME_NONNULL_END
