///
/// Copyright (c) 2016 Dropbox, Inc. All rights reserved.
///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>

#import "DBSerializableProtocol.h"

@class DBTEAMLOGTeamBrandingPolicy;
@class DBTEAMLOGTeamBrandingPolicyChangedDetails;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - API Object

///
/// The `TeamBrandingPolicyChangedDetails` struct.
///
/// Changed team branding policy for team.
///
/// This class implements the `DBSerializable` protocol (serialize and
/// deserialize instance methods), which is required for all Obj-C SDK API route
/// objects.
///
@interface DBTEAMLOGTeamBrandingPolicyChangedDetails : NSObject <DBSerializable, NSCopying>

#pragma mark - Instance fields

/// New team branding policy.
@property (nonatomic, readonly) DBTEAMLOGTeamBrandingPolicy *dNewValue;

/// Previous team branding policy.
@property (nonatomic, readonly) DBTEAMLOGTeamBrandingPolicy *previousValue;

#pragma mark - Constructors

///
/// Full constructor for the struct (exposes all instance variables).
///
/// @param dNewValue New team branding policy.
/// @param previousValue Previous team branding policy.
///
/// @return An initialized instance.
///
- (instancetype)initWithDNewValue:(DBTEAMLOGTeamBrandingPolicy *)dNewValue
                    previousValue:(DBTEAMLOGTeamBrandingPolicy *)previousValue;

- (instancetype)init NS_UNAVAILABLE;

@end

#pragma mark - Serializer Object

///
/// The serialization class for the `TeamBrandingPolicyChangedDetails` struct.
///
@interface DBTEAMLOGTeamBrandingPolicyChangedDetailsSerializer : NSObject

///
/// Serializes `DBTEAMLOGTeamBrandingPolicyChangedDetails` instances.
///
/// @param instance An instance of the
/// `DBTEAMLOGTeamBrandingPolicyChangedDetails` API object.
///
/// @return A json-compatible dictionary representation of the
/// `DBTEAMLOGTeamBrandingPolicyChangedDetails` API object.
///
+ (nullable NSDictionary<NSString *, id> *)serialize:(DBTEAMLOGTeamBrandingPolicyChangedDetails *)instance;

///
/// Deserializes `DBTEAMLOGTeamBrandingPolicyChangedDetails` instances.
///
/// @param dict A json-compatible dictionary representation of the
/// `DBTEAMLOGTeamBrandingPolicyChangedDetails` API object.
///
/// @return An instantiation of the `DBTEAMLOGTeamBrandingPolicyChangedDetails`
/// object.
///
+ (DBTEAMLOGTeamBrandingPolicyChangedDetails *)deserialize:(NSDictionary<NSString *, id> *)dict;

@end

NS_ASSUME_NONNULL_END
