///
/// Copyright (c) 2016 Dropbox, Inc. All rights reserved.
///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>

#import "DBSerializableProtocol.h"

@class DBTEAMLOGCaptureTranscriptPolicy;
@class DBTEAMLOGCaptureTranscriptPolicyChangedDetails;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - API Object

///
/// The `CaptureTranscriptPolicyChangedDetails` struct.
///
/// Changed Capture transcription policy for team.
///
/// This class implements the `DBSerializable` protocol (serialize and
/// deserialize instance methods), which is required for all Obj-C SDK API route
/// objects.
///
@interface DBTEAMLOGCaptureTranscriptPolicyChangedDetails : NSObject <DBSerializable, NSCopying>

#pragma mark - Instance fields

/// To.
@property (nonatomic, readonly) DBTEAMLOGCaptureTranscriptPolicy *dNewValue;

/// From.
@property (nonatomic, readonly) DBTEAMLOGCaptureTranscriptPolicy *previousValue;

#pragma mark - Constructors

///
/// Full constructor for the struct (exposes all instance variables).
///
/// @param dNewValue To.
/// @param previousValue From.
///
/// @return An initialized instance.
///
- (instancetype)initWithDNewValue:(DBTEAMLOGCaptureTranscriptPolicy *)dNewValue
                    previousValue:(DBTEAMLOGCaptureTranscriptPolicy *)previousValue;

- (instancetype)init NS_UNAVAILABLE;

@end

#pragma mark - Serializer Object

///
/// The serialization class for the `CaptureTranscriptPolicyChangedDetails`
/// struct.
///
@interface DBTEAMLOGCaptureTranscriptPolicyChangedDetailsSerializer : NSObject

///
/// Serializes `DBTEAMLOGCaptureTranscriptPolicyChangedDetails` instances.
///
/// @param instance An instance of the
/// `DBTEAMLOGCaptureTranscriptPolicyChangedDetails` API object.
///
/// @return A json-compatible dictionary representation of the
/// `DBTEAMLOGCaptureTranscriptPolicyChangedDetails` API object.
///
+ (nullable NSDictionary<NSString *, id> *)serialize:(DBTEAMLOGCaptureTranscriptPolicyChangedDetails *)instance;

///
/// Deserializes `DBTEAMLOGCaptureTranscriptPolicyChangedDetails` instances.
///
/// @param dict A json-compatible dictionary representation of the
/// `DBTEAMLOGCaptureTranscriptPolicyChangedDetails` API object.
///
/// @return An instantiation of the
/// `DBTEAMLOGCaptureTranscriptPolicyChangedDetails` object.
///
+ (DBTEAMLOGCaptureTranscriptPolicyChangedDetails *)deserialize:(NSDictionary<NSString *, id> *)dict;

@end

NS_ASSUME_NONNULL_END
