///
/// Copyright (c) 2016 Dropbox, Inc. All rights reserved.
///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>

#import "DBSerializableProtocol.h"

@class DBTEAMLOGUserTagsRemovedDetails;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - API Object

///
/// The `UserTagsRemovedDetails` struct.
///
/// Removed tags.
///
/// This class implements the `DBSerializable` protocol (serialize and
/// deserialize instance methods), which is required for all Obj-C SDK API route
/// objects.
///
@interface DBTEAMLOGUserTagsRemovedDetails : NSObject <DBSerializable, NSCopying>

#pragma mark - Instance fields

/// values.
@property (nonatomic, readonly) NSArray<NSString *> *values;

#pragma mark - Constructors

///
/// Full constructor for the struct (exposes all instance variables).
///
/// @param values values.
///
/// @return An initialized instance.
///
- (instancetype)initWithValues:(NSArray<NSString *> *)values;

- (instancetype)init NS_UNAVAILABLE;

@end

#pragma mark - Serializer Object

///
/// The serialization class for the `UserTagsRemovedDetails` struct.
///
@interface DBTEAMLOGUserTagsRemovedDetailsSerializer : NSObject

///
/// Serializes `DBTEAMLOGUserTagsRemovedDetails` instances.
///
/// @param instance An instance of the `DBTEAMLOGUserTagsRemovedDetails` API
/// object.
///
/// @return A json-compatible dictionary representation of the
/// `DBTEAMLOGUserTagsRemovedDetails` API object.
///
+ (nullable NSDictionary<NSString *, id> *)serialize:(DBTEAMLOGUserTagsRemovedDetails *)instance;

///
/// Deserializes `DBTEAMLOGUserTagsRemovedDetails` instances.
///
/// @param dict A json-compatible dictionary representation of the
/// `DBTEAMLOGUserTagsRemovedDetails` API object.
///
/// @return An instantiation of the `DBTEAMLOGUserTagsRemovedDetails` object.
///
+ (DBTEAMLOGUserTagsRemovedDetails *)deserialize:(NSDictionary<NSString *, id> *)dict;

@end

NS_ASSUME_NONNULL_END
