///
/// Copyright (c) 2016 Dropbox, Inc. All rights reserved.
///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>

#import "DBSerializableProtocol.h"

@class DBTEAMSharingAllowlistAddResponse;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - API Object

///
/// The `SharingAllowlistAddResponse` struct.
///
/// This struct is empty. The comment here is intentionally emitted to avoid
/// indentation issues with Stone.
///
/// This class implements the `DBSerializable` protocol (serialize and
/// deserialize instance methods), which is required for all Obj-C SDK API route
/// objects.
///
@interface DBTEAMSharingAllowlistAddResponse : NSObject <DBSerializable, NSCopying>

#pragma mark - Instance fields

#pragma mark - Constructors

///
/// Full constructor for the struct (exposes all instance variables).
///
/// @return An initialized instance.
///
- (instancetype)initDefault;

- (instancetype)init NS_UNAVAILABLE;

@end

#pragma mark - Serializer Object

///
/// The serialization class for the `SharingAllowlistAddResponse` struct.
///
@interface DBTEAMSharingAllowlistAddResponseSerializer : NSObject

///
/// Serializes `DBTEAMSharingAllowlistAddResponse` instances.
///
/// @param instance An instance of the `DBTEAMSharingAllowlistAddResponse` API
/// object.
///
/// @return A json-compatible dictionary representation of the
/// `DBTEAMSharingAllowlistAddResponse` API object.
///
+ (nullable NSDictionary<NSString *, id> *)serialize:(DBTEAMSharingAllowlistAddResponse *)instance;

///
/// Deserializes `DBTEAMSharingAllowlistAddResponse` instances.
///
/// @param dict A json-compatible dictionary representation of the
/// `DBTEAMSharingAllowlistAddResponse` API object.
///
/// @return An instantiation of the `DBTEAMSharingAllowlistAddResponse` object.
///
+ (DBTEAMSharingAllowlistAddResponse *)deserialize:(NSDictionary<NSString *, id> *)dict;

@end

NS_ASSUME_NONNULL_END
