///
/// Copyright (c) 2016 Dropbox, Inc. All rights reserved.
///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>

#import "DBSerializableProtocol.h"

@class DBTEAMLOGUndoNamingConventionDetails;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - API Object

///
/// The `UndoNamingConventionDetails` struct.
///
/// Reverted naming convention.
///
/// This class implements the `DBSerializable` protocol (serialize and
/// deserialize instance methods), which is required for all Obj-C SDK API route
/// objects.
///
@interface DBTEAMLOGUndoNamingConventionDetails : NSObject <DBSerializable, NSCopying>

#pragma mark - Instance fields

#pragma mark - Constructors

///
/// Full constructor for the struct (exposes all instance variables).
///
/// @return An initialized instance.
///
- (instancetype)initDefault;

- (instancetype)init NS_UNAVAILABLE;

@end

#pragma mark - Serializer Object

///
/// The serialization class for the `UndoNamingConventionDetails` struct.
///
@interface DBTEAMLOGUndoNamingConventionDetailsSerializer : NSObject

///
/// Serializes `DBTEAMLOGUndoNamingConventionDetails` instances.
///
/// @param instance An instance of the `DBTEAMLOGUndoNamingConventionDetails`
/// API object.
///
/// @return A json-compatible dictionary representation of the
/// `DBTEAMLOGUndoNamingConventionDetails` API object.
///
+ (nullable NSDictionary<NSString *, id> *)serialize:(DBTEAMLOGUndoNamingConventionDetails *)instance;

///
/// Deserializes `DBTEAMLOGUndoNamingConventionDetails` instances.
///
/// @param dict A json-compatible dictionary representation of the
/// `DBTEAMLOGUndoNamingConventionDetails` API object.
///
/// @return An instantiation of the `DBTEAMLOGUndoNamingConventionDetails`
/// object.
///
+ (DBTEAMLOGUndoNamingConventionDetails *)deserialize:(NSDictionary<NSString *, id> *)dict;

@end

NS_ASSUME_NONNULL_END
