name: Xcode Build
on:
  pull_request:
    branches: ["master"]
    paths: ["!docs/**", "!.github/**", "!**.md", "!**.yml"]
  push:
    branches: ["master"]
    paths: ["!docs/**", "!.github/**", "!**.md", "!**.yml"]
jobs:
  build:
    name: Build AppBox
    runs-on: macos-latest
    steps:
      - name: Checkout repository
		uses: actions/checkout@v4
      - name: Use latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Build App
        run: |
          set -o pipefail
          xcodebuild clean build -project AppBox.xcodeproj -scheme AppBox CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO 2>&1 | tee build.log
          if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "::error::Build failed"
            exit 1
          fi
